version: '3'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
            - /var/www/storage/app/public/:/var/www/storage/app/public/
            - /var/www/storage/app/public/:/var/www/public/storage
        ports:
            - "8000:80"
        depends_on:
            - app
        container_name: omg_nginx
        networks:
            - application

    app:
        build:
            context: ./
            dockerfile: ./_docker/app/Dockerfile
        volumes:
            - ./:/var/www
            - /var/www/storage/app/public/:/var/www/storage/app/public/
            - ./_docker/app/zzz-xdebug.ini:/usr/local/etc/php/conf.d/zzz-xdebug.ini
            - /var/www/storage/app/public/:/var/www/public/storage
        container_name: omg_app
        environment:
            DB_CONNECTION: pgsql
            DB_HOST: omg_db
            DB_PORT: 5432
            DB_DATABASE: laravel
            DB_USERNAME: root
            DB_PASSWORD: password
            REDIS_HOST: omg_redis
            REDIS_PORT: 6379
            QUEUE_CONNECTION: redis
            PHP_IDE_CONFIG: "serverName=OMG"
        depends_on:
            - db
            - redis
        networks:
            - application

    db:
        image: postgres:15.1
        restart: always
        volumes:
            - /var/lib/postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
            POSTGRES_DB: laravel
        container_name: omg_db
        ports:
            - "5432:5432"
        networks:
            - application

    redis:
        image: 'redis:alpine'
        ports:
        - '${FORWARD_REDIS_PORT:-6379}:6379'
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            retries: 3
            timeout: 5s
        container_name: omg_redis
        networks:
            - application

networks:
    application:
        driver: bridge






